name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Initialize go.mod
      run: |
        cd server
        go mod init go-opddrdesk-apis-server
        go mod tidy

    - name: Build
      working-directory: ./server
      run: go build -v .

    - name: Test
      working-directory: ./server
      run: go test -v .
